### ISSUE TITLE
PBI 7: Create Sign Up page and Create Your Profile page

### ISSUE THREAD

**Issue by linchristina03** [COSC481W-2024Fall/Swoop-In#12]
User Story:
Margaret is a new user to the Swoop-In application. She would like to be able to create and account to sign up and customize her profile to start connecting with other fellow EMU people.

Persona: Margaret is an EMU student that would llike to start using the Swoop-In app.
Feature: Make the Sign up page for Swoop-In and the Create Your Profile page.
Business Value: This allows the new user to be able to access the app and create their profile to start connecting with other users.

Tasks:
- [ ] Create a Sign Up page UI that matches with existing pages
       - check for already existing users   
- [ ] Create the buttons/links to sign up to add the information to the database (Abhi PBI 5)
- [ ] Create the Create Your Profile page UI that matches with existing pages.
- [ ] Create the necessary text fields and drop downs for the profile requirements
       - firstName
       - lastName
       - images (array)
       - age
       - bio
       - gender
       - preferredGender
       - preferredAge
       - major  

Acceptance Criteria:
- Sign Up Submit button is clicked new user gets routed to the Create Your Profile page.
- Data from Sign up is added to the data base (managed by Abhi PBI 5).
- Create Your Profile Submit button is clicked new user will be routed to the home page.
- Data from Create Your Profile Page is added to the database (managed by Abhi PBI 5).

**Comment by sjiang1** [comment]
1. This PBI was not on the GitHub project board (I added it.). In the future, please make sure to add the PBIs to the project board.
2. Add a label "sprint-2" for this issue
3. Add an assignee
4. Who's going to be responsible for the database?
5. Please double check the start and end date on this issue page.
