### ISSUE TITLE
PBI 8: Navbar Page Functionality

### ISSUE THREAD

**Issue by mdlaroy** [COSC481W-2024Fall/Swoop-In#13]
User Story:
Bela is a new user to the Swoop-In application. She would like to be able to navigate the different pages and see what other functionality is offered.

Persona: Bela is an EMU student that would llike navigate and explore the app.
Feature: Flesh out the other navbar pages and setup for future functionality
Business Value: This allows the new user to be able to access the different pages and sets the pages for further features to be added.

Tasks:

- [x] Create UI for match page
- [x] Create UI for profile page
- [ ] Create UI for chat page
- [x] Add navbar to each page for ease of use

Acceptance Criteria:

- user can navigate between pages from navbar
- navbar on each page is fully function
- each page has a consistent UI that aligns with the theme of the app but also the functionality of the page
- match page will display a dummy match (for testing use) where the user can see the pool of candidates
- chat page will display a dummy chat section (for testing use) where the user can see active chats
- profile page will display the content of the user and capable of editing their profile; user will be able to add pictures, change their name, and change bio

**Comment by sjiang1** [comment]
1. Please add a label "sprint-2"
2. Who's going to be responsible for the database?
3. Please double check the start and end dates on this issue page

**Comment by sjiang1** [comment]
This PBI was not on the GitHub project board (I added it.). In the future, please make sure to add the PBIs to the project board.
